urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^$', 'shortener.views.index'),    
    (r'^admin/(.*)', admin.site.root),    
    (r'^submit/$', 'shortener.views.submit'),
    (r'^(?P<base62_id>\w+)$', 'shortener.views.follow'),
    (r'^info/(?P<base62_id>\w+)$', 'shortener.views.info'),    

    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
      {'document_root': settings.STATIC_DOC_ROOT}),
)

shortener/models.py
import datetime

from django.db import models
from django.conf import settings
#from django.contrib.auth.models import User
from django import forms

from urlweb.shortener.baseconv import base62

class Link(models.Model):
    """
    Model that represents a shortened URL

    # Initialize by deleting all Link objects
    >>> Link.objects.all().delete()
    
    # Create some Link objects
    >>> link1 = Link.objects.create(url="http://www.google.com/")
    >>> link2 = Link.objects.create(url="http://www.nileshk.com/")

    # Get base 62 representation of id
    >>> link1.to_base62()
    'B'
    >>> link2.to_base62()
    'C'
    
    # Set SITE_BASE_URL to something specific
    >>> settings.SITE_BASE_URL = 'http://uu4.us/'

    # Get short URL's
    >>> link1.short_url()
    'http://uu4.us/B'
    >>> link2.short_url()
    'http://uu4.us/C'

    # Test usage_count
    >>> link1.usage_count
    0
    >>> link1.usage_count += 1
    >>> link1.usage_count
    1

    """
    url = models.URLField(verify_exists=True, unique=True)
    date_submitted = models.DateTimeField(auto_now_add=True)
    usage_count = models.IntegerField(default=0)

    def to_base62(self):
        return base62.from_decimal(self.id)

    def short_url(self):
        return settings.SITE_BASE_URL + self.to_base62()
    
    def __unicode__(self):
        return self.to_base62() + ' : ' + self.url

class LinkSubmitForm(forms.Form):
    u = forms.URLField(verify_exists=True,
                       label='URL to be shortened:',
                       )

shortener/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.views.generic import list_detail
from django.shortcuts import get_object_or_404, get_list_or_404, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.utils import simplejson
from django.template import RequestContext
from django.views.decorators.http import require_POST
from django.db import transaction
from django.conf import settings

from urlweb.shortener.baseconv import base62
from urlweb.shortener.models import Link, LinkSubmitForm

def follow(request, base62_id):
    """ 
    View which gets the link for the given base62_id value
    and redirects to it.
    """
    key = base62.to_decimal(base62_id)
    link = get_object_or_404(Link, pk = key)
    link.usage_count += 1
    link.save()
    return HttpResponsePermanentRedirect(link.url)

def default_values(request, link_form=None):
    """ 
    Return a new object with the default values that are typically
    returned in a request.
    """
    if not link_form:
        link_form = LinkSubmitForm()
    allowed_to_submit = is_allowed_to_submit(request)
    return { 'show_bookmarklet': allowed_to_submit,
             'show_url_form': allowed_to_submit,
             'site_name': settings.SITE_NAME,
             'site_base_url': settings.SITE_BASE_URL,
             'link_form': link_form,
             }

def info(request, base62_id):
    """
    View which shows information on a particular link
    """
    key = base62.to_decimal(base62_id)
    link = get_object_or_404(Link, pk = key)
    values = default_values(request)
    values['link'] = link
    return render_to_response(
        'shortener/link_info.html',
        values,
        context_instance=RequestContext(request))

def submit(request):
    """
    View for submitting a URL
    """
    if settings.REQUIRE_LOGIN and not request.user.is_authenticated():
        # TODO redirect to an error page
        raise Http404
    url = None
    link_form = None
    if request.GET:
        link_form = LinkSubmitForm(request.GET)
    elif request.POST:
        link_form = LinkSubmitForm(request.POST)
    if link_form and link_form.is_valid():
        url = link_form.cleaned_data['u']
        link = None
        try:
            link = Link.objects.get(url = url)
        except Link.DoesNotExist:
            pass
        if link == None:
            new_link = Link(url = url)
            new_link.save()
            link = new_link
        values = default_values(request)
        values['link'] = link
        return render_to_response(
            'shortener/submit_success.html',
            values,
            context_instance=RequestContext(request))
    values = default_values(request, link_form=link_form)
    return render_to_response(
        'shortener/submit_failed.html',
        values,
        context_instance=RequestContext(request))

def index(request):
    """
    View for main page (lists recent and popular links)
    """
    values = default_values(request)
    values['recent_links'] = Link.objects.all().order_by('-date_submitted')[0:10]
    values['most_popular_links'] = Link.objects.all().order_by('-usage_count')[0:10]
    return render_to_response(
        'shortener/index.html',
        values,
        context_instance=RequestContext(request))

def is_allowed_to_submit(request):
    """
    Return true if user is allowed to submit URLs
    """
    return not settings.REQUIRE_LOGIN or request.user.is_authenticated()

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>{% block title %}URLs{% endblock %}</title>

    <link rel="stylesheet" 
          href="/static/css/blueprint/screen.css" 
          type="text/css" media="screen, projection"/>

    <link rel="stylesheet" 
          href="static/css/blueprint/print.css" type="text/css" media="print"/>

    <!--[if lt IE 8]>
    <link rel="stylesheet" 
          href="/static/css/blueprint/ie.css" 
          type="text/css" media="screen, projection"/>
    <![endif]-->
    
    <link rel="stylesheet" 
          href="/static/css/blueprint/plugins/fancy-type/screen.css"
          type="text/css" media="screen, projection"/>
    
    <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js">
    </script>
    
    {% block extra_head %}
    {% endblock %}
  </head>

  <body>
    <div class="container">
      <div class="span-24 last">
        <h1><a href="{{ site_base_url }}">{{ site_name }}</a></h1>
        <hr/>
      </div>
      <div class="span-24 last">
        {% block content %}{% endblock %}
        <hr/>
      </div>

      <div class="span-19 colborder">
        {% if show_url_form %}
        {% block url_form %}
        <form name="url_form" action="/submit/" method="get">
          {{ link_form.as_p }}
          <input type="submit" value="Submit" />
        </form>
        {% endblock %}
        {% endif %}
      </div>
      <div class="span-4 last">
        {% if show_bookmarklet %}
        {% block bookmarklet %}
        <br/>
        Bookmarklet (drag this to your bookmarks bar):<br/>
        <a href="javascript:(function(){var a=window,b=document,c=encodeURIComponent;d=a.open(&#39;{{ site_base_url }}submit/?u=&#39;+c(b.location));})();">Shorten with {{ site_name }}</a>
        {% endblock %}
        {% endif %}
      </div>
      {% block extra_body %}{% endblock %}
    </div>
  </body>
</html>

templates/shortener/index.html
{% extends "base.html" %}
{% block content %}
<h2>Recent Links</h2>
<ul>
{% for link in recent_links %}
<li><a href="{{ link.short_url }}">{{ link.url }}</a> (Score: {{ link.usage_count }})
(<a href="{% url shortener.views.info link.to_base62 %}">Info</a>)</li>
{% endfor %}
</ul>

<h2>Most Popular Links</h2>
<ul>
{% for link in most_popular_links %}
<li><a href="{{ link.short_url }}">{{ link.url }}</a> (Score: {{ link.usage_count }})
(<a href="{% url shortener.views.info link.to_base62 %}">Info</a>)</li>
{% endfor %}
</ul>
{% endblock %}

{% block extra_body %}
<script>
$(document).ready(
  function() {
    $("#id_u").focus().select();
  });
</script>  
{% endblock %}

templates/shortener/link_info.html
{% extends "base.html" %}

{% block title %}Link info{% endblock %}

{% block content %}
<p>
<a href="{{ link.short_url }}">{{ link.url }}</a> (Score: {{ link.usage_count }})
<br/>
<br/>
Submitted on: {{ link.date_submitted|date:"M d, Y" }}
</p>
{% endblock %}

templates/shortener/submit_failed.html
{% extends "base.html" %}

{% block title %}URL submission failed{% endblock %}

{% block content %}
<h2>URL submission failed</h2>
{% endblock %}

{% block extra_body %}
<script>
$(document).ready(
  function() {
    $("#id_u").focus().select();
  });
</script>  
{% endblock %}

templates/shortener/submit_success.html
{% extends "base.html" %}

{% block title %}URL shortened{% endblock %}

{% block content %}
The following URL:<br/>
<pre>
{{ link.url }}
</pre>
<br/>
Was shortened to:<br/>
<input id="link" type="text" size="30"
       value="{{ link.short_url }}"/>
<br/>
<br/>
Score: {{ link.usage_count }}
(<a href="{% url shortener.views.info link.to_base62 %}">Info</a>)
<br/>
<br/>
{% endblock %}

{% block extra_body %}
<script>
$(document).ready(
  function() {
    $("#link").focus().select();
  });
</script>  
{% endblock %}